#! /bin/sh

fcitx5 &
pulseaudio &
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/Pictures/wallpapers.jpg

xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI #VII VIII IX X

bspc config border_width         2
bspc config window_gap          8

bspc config normal_border_color \#FFFFFF
bspc config focused_border_color \#A66434

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Blender desktop='^6' #state=fullscreen
bspc rule -a FreeCAD desktop='^3' #state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#~/.config/polybar/launch.sh

~/.config/lemonbar/launch.sh
